### ISSUE TITLE
Button hover

### ISSUE THREAD

**Issue by akramjonnuriddinov** [IbragimovOlimjon/004-Articles-maketi#1]
![image](https://user-images.githubusercontent.com/99048411/158072221-2d9aa1cc-ca2c-4ffe-b71a-10ae74ec6e1f.png)
Buttonga hover holati uchun 0.8 berish kerak. Active holati uchun esa 0.6 berish kerak.

**Comment by IbragimovOlimjon** [comment]
butonning hover holatidagi ko'rsatilgan hatolar to'g'irlandi
