### ISSUE TITLE
Focus style

### ISSUE THREAD

**Issue by akramjonnuriddinov** [IbragimovOlimjon/004-Articles-maketi#2]
![image](https://user-images.githubusercontent.com/99048411/158072443-ccf12403-0a8b-4d6f-8873-424977becc06.png)
Saytning tab bilan yurish holatini stillarini to'g'rilash kerak.

**Comment by IbragimovOlimjon** [comment]
chunarli fokus holatiga stillar berildi!

**Comment by IbragimovOlimjon** [comment]
chunarli fokus holatiga stillar berildi!
