### ISSUE TITLE
Hero padding

### ISSUE THREAD

**Issue by akramjonnuriddinov** [IbragimovOlimjon/004-Articles-maketi#3]
![image](https://user-images.githubusercontent.com/99048411/158072654-930fd199-8659-4716-9507-ba6e845c5ec7.png)
Hero qismining padding yuqori va pastdan 326pxdan. Shuni to'g'rilash kerak.

**Comment by IbragimovOlimjon** [comment]
bu yo'lni  yechim videosidan ko'rib chiqib qo'shdim qo'llanilishidan maqsad video darsda ko'rsatilgan)
